# Define the PHP executable and commonly used paths
PHP := php
PHPUNIT := ./vendor/bin/phpunit
RECTOR := ./vendor/bin/rector

# Default target
all: test

# PHPUnit target
test:
	@echo "Running PHPUnit tests..."
	$(PHPUNIT) --configuration phpunit.xml --colors=always

# Rector targets for code refactoring
rector:
	@echo "Running Rector refactoring..."
	$(RECTOR) process src --dry-run --clear-cache --config rector.php

rector-fix:
	@echo "Applying Rector refactoring..."
	$(RECTOR) process src --clear-cache --config rector.php

# Clean up cache generated by Rector and PHPUnit
clean:
	@echo "Cleaning Rector and PHPUnit caches..."
	rm -rf .rector/cache
	rm -rf .phpunit.result.cache

# Run both test and rector targets
check: test rector

# Help menu
help:
	@echo "Available targets:"
	@echo "  test          - Run PHPUnit tests with default configuration"
	@echo "  rector        - Run Rector in dry-run mode"
	@echo "  rector-fix    - Apply Rector refactoring"
	@echo "  clean         - Remove cache for Rector and PHPUnit"
	@echo "  check         - Run both tests and Rector in dry-run mode"

# Phony targets to prevent issues with files named like targets
.PHONY: all test rector rector-fix clean check help
