# Define the PHP executable and commonly used paths
PHP := php
PHPUNIT := ./vendor/bin/phpunit
RECTOR := ./vendor/bin/rector
PHPCS := ./vendor/bin/phpcs
PHPCBF := ./vendor/bin/phpcbf
PHPCSARGS := --standard=PSR12 --exclude=Generic.NamingConventions.UpperCaseConstantName,PSR1.Methods.CamelCapsMethodName,PSR2.Methods.MethodDeclaration

# Default target
all: help

# PHPUnit target
test:
	@echo "Running PHPUnit tests..."
	$(PHPUNIT) --configuration phpunit.xml --colors=always

# Rector targets for code refactoring
rector:
	@echo "Running Rector refactoring..."
	$(RECTOR) process src --dry-run --clear-cache --config rector.php

rector-fix:
	@echo "Applying Rector refactoring..."
	$(RECTOR) process src --clear-cache --config rector.php

# PHPCS target for linting
lint:
	@echo "Running PHP CodeSniffer (PHPCS) for linting..."
	$(PHPCS) $(PHPCSARGS) src/


# PHPCBF target for auto-fixing code style issues
lint-fix:
	@echo "Running PHP Code Beautifier and Fixer (PHPCBF) for auto-fixing..."
	$(PHPCBF) $(PHPCSARGS) src/

# Clean up cache generated by Rector, PHPUnit, and PHPCS
clean:
	@echo "Cleaning caches for Rector, PHPUnit, and PHPCS..."
	rm -rf .rector/cache
	rm -rf .phpunit.result.cache
	rm -rf .phpcs.cache

# Run both test and lint targets
check: test lint

# Help menu
help:
	@echo "Available targets:"
	@echo "  test          - Run PHPUnit tests with default configuration"
	@echo "  rector        - Run Rector in dry-run mode"
	@echo "  rector-fix    - Apply Rector refactoring"
	@echo "  lint          - Run PHP CodeSniffer (PHPCS) for code style checks"
	@echo "  lint-fix      - Auto-fix code style issues with PHP Code Beautifier (PHPCBF)"
	@echo "  clean         - Remove cache for Rector, PHPUnit, and PHPCS"
	@echo "  check         - Run both tests and linting in dry-run mode"

# Phony targets to prevent issues with files named like targets
.PHONY: all test rector rector-fix lint lint-fix clean check help
