name: CI
on: [push]
jobs:
    build-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['8.3', '8.4']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .env
              run: cp .env.example .env

            - name: Setup ownership
              run: git config --global --add safe.directory /app

            - name: Replace placeholders with GitHub Secrets
              run: |
                sed -i "s/BLUEM_SENDER_ID=S/BLUEM_SENDER_ID=${{ secrets.BLUEM_SENDER_ID }}/g" .env
                sed -i "s/BLUEM_TEST_ACCESS_TOKEN=/BLUEM_TEST_ACCESS_TOKEN=${{ secrets.BLUEM_TEST_ACCESS_TOKEN }}/g" .env

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl
                  coverage: xdebug

            - name: Run composer
              uses: php-actions/composer@v6
              with:
                  php_version: ${{ matrix.php-version }}

            - name: PHPCS Lint
              run: make lint

            - name: PHPUnit Tests
              uses: php-actions/phpunit@v4
              with:
                  php_version: ${{ matrix.php-version }}
                  version: 11
                  bootstrap: ./vendor/autoload.php
                  configuration: ./.github/workflows/phpunit.xml
